### ISSUE TITLE
Support for Separator Characters

### ISSUE THREAD

**Issue by rbong** [rbong/vim-crystalline#1]
As [PM_ME_IRL on reddit](https://www.reddit.com/r/vim/comments/bqlhx3/vimcrystalline_a_new_vim_statuslinetabline_helper/eo5ldpb/) brought attention to, separator characters are not currently supported.

I'd like to add them in, but it will require new highlight groups for every potential boundary between highlight groups, because you need to set the foreground to one color and the background to the other. I don't think it will be practical for users to have to sort through all of those highlight groups and find the one they need, or to use different functions for multiple mode highlight groups.

They'll also have to define the separators themselves, which will be quite verbose.

I need suggestions and feedback. If anyone can think of how to add separators and still keep the plugin nice and clean, I'm all ears.

**Comment by rbong** [comment]
I think I have found a nice way to do this.
It should be fairly easy for users to deal with and will have very little in the terms of performance impact.
It should be done in the next week or two if work doesn't get in the way.

The user interface will look like this:

```vim
function! StatusLine(current)
  return (a:current ? crystalline#mode() . crystalline#right_mode_sep('') : '%#CrystallineInactive#')
        \ . ' %f%h%w%m%r '
        \ . (a:current ? crystalline#right_sep('', 'Fill') : '')
        \ . '%=' . (a:current ? crystalline#left_sep('', 'Fill') . ' %{&spell?"SPELL ":""}' . crystalline#left_mode_sep('Fill') : '')
        \ . ' %{&ft}[%{&enc}][%{&ffs}] %l/%L %c%V %P '
endfunction

let g:crystalline_enable_sep = 1
```

So, as you can see, you can generate separators using `crystalline#[right|left]_sep(group1, group2)` and with `crystalline#[right|left]_mode_sep(group)`.
The groups passed to the functions are just the highlight group names with `Crystalline` omitted.
All of the correct highlight items will be added for the separator and the next highlight group.

For instance: `crystalline#right_sep('', 'Fill')` returns `%#CrystallineToFillSeparator#>%#CrystallineFill#` so you can place it between the `%#Crystalline#` part of the statusbar and the desired `%#CrystallineFill#` part of the statusbar.

Tab separators are automatically handled.

Separator characters will be customizable via global variables.

The technical impact is as follows:

Highlight groups will now be generated dynamically.
This will have the added benefit of making themes easier to write.

With separators enabled, many extra highlight groups will be generated automatically for the separators, since each boundary between groups needs its own highlight group.

Themes will be generated in a single `exec` command so there will be very little performance impact on startup even with separators on, and even less with them off (I have already measured this).

Runtime impact is not fully known but should be even more negligible since generating the highlight groups is the expensive part.
I have a rough implementation with most of the most expensive separators implemented and there is no runtime impact.

Let me know if anyone has any questions or concerns.

**Comment by rbong** [comment]
You can try this now on the dev branch:

```vim
function! StatusLine(current)
  return (a:current ? crystalline#mode() . crystalline#right_mode_sep('') : '%#CrystallineInactive#')
        \ . ' %f%h%w%m%r '
        \ . (a:current ? crystalline#right_sep('', 'Fill') . ' %{fugitive#head()}' : '')
        \ . '%=' . (a:current ? crystalline#left_sep('', 'Fill') . ' %{&spell?"SPELL ":""}' . crystalline#left_mode_sep('') : '')
        \ . ' %{&ft}[%{&enc}][%{&ffs}] %l/%L %c%V %P '
endfunction

function! TabLine()
  let l:vimlabel = has("nvim") ?  " NVIM " : " VIM "
  return crystalline#bufferline(2, len(l:vimlabel), 1) . '%=%#CrystallineTab# ' . l:vimlabel
endfunction

let g:crystalline_enable_sep = 1
let g:crystalline_statusline_fn = 'StatusLine'
let g:crystalline_tabline_fn = 'TabLine'
let g:crystalline_theme = 'default'

set showtabline=2
set laststatus=2

call plug#begin()
Plug 'rbong/vim-crystalline', { 'branch': 'dev' }
" only needed if you use %{fugitive#head()}
Plug 'tpope/vim-fugitive'
call plug#end()
```

**Comment by rbong** [comment]
This should now be available on master

**Comment by unnikrishnanta** [comment]
The separators don't show up for me. Instead only question marks ("?") appear.

**Comment by rbong** [comment]
@unnikrishnanta your font may not support the separator characters. Do you have a powerline font installed and enabled? Do the fancy separator characters appear for you on other plugins?

Does it work if you do:

```vim
let g:crystalline_separators = ['>', '<']
```

**Comment by unnikrishnanta** [comment]
Ah yes! Followed by configuring them in iTerm2. It works great now. Thank you :)
