### ISSUE TITLE
Specify seperator character

### ISSUE THREAD

**Issue by erikdsjostrom** [rbong/vim-crystalline#10]
Is there any way to change the default separator character?

**Comment by rbong** [comment]
Yup, just set the global variables `g:crystalline_separators` and `g:crystalline_tab_separator` in your .vimrc before the plugin loads (before calling `Plug#end()` if you are using `vim-plugged`).

Refer to these lines of code that set the defaults: https://github.com/rbong/vim-crystalline/blob/82f24719b49786017dadafea410b1660ae027132/plugin/crystalline.vim#L56-L62

Example:

```vim
let g:crystalline_separators = ['>', '<']
let g:crystalline_tab_separator = '>'
```

**Comment by rbong** [comment]
Please feel free to reopen if that doesn't fully answer the question.
