### ISSUE TITLE
Use fileformat (not fileformats) in README.md examples

### ISSUE THREAD

**Issue by osamuaoki** [rbong/vim-crystalline#13]
Thanks for your clean and neat tool.

I see code such as: `let l:s .= ' %{&ft}[%{&enc}][%{&ffs}] %l/%L %c%V %P '` in README.md.   `&ffs` is short for `fileformats` which gives the end-of-line (<EOL>) formats that will be tried.  In my case, it is system default as fileformats=unix,dos on unix.  What we usually want and graphic example seems to show are `&fileformat` (or its short form `&ff`).

So I think `%s/ffs/fileformat/g` is needed for README.md.

Or is this your intentional choice?

**Comment by rbong** [comment]
Good catch! Should be fixed now. Feel free to reopen if it's not. Unfortunate that this error probably got copied to many vimrc's.
