### ISSUE TITLE
Use fileencoding (not enc) in README.md examples

### ISSUE THREAD

**Issue by osamuaoki** [rbong/vim-crystalline#14]
Hi again.

Usually, fileencoding is what you want.  (Not how vim handles internally).

So `s/enc/fileencoding/g` ?

Also, I don't feel like having vim-fugitive just for this function.  So I use different plugin (This is just FYI). 
```
  " If itchyny/vim-gitbranch is available
  let l:b = gitbranch#name()
  " If tpope/vim-fugitive is available
  "let l:b = fugitive#head()
```

**Comment by rbong** [comment]
Thanks! Another good catch. I think you're right. All instances should be fixed. I was thinking about including your example in the readme but I think I'm happy with just including a single example for integrating with other plugins for now. Please do let me know if you find anything else.

**Comment by osamuaoki** [comment]
My settings are WIP.

Please look at:
https://github.com/osamuaoki/dot-vim

Especially conf/preconf.available/vim-crystalline

I now made to chose which ever available if available ...

**Comment by rbong** [comment]
@osamuaoki Very nice config! Keep in mind that executing something outside of a statusline item will be in the context of the currently active buffer, and executing something inside of a statusline item will be in the context of the buffer that holds the statusline, despite the fact that `a:current` and `a:width` correspond to the buffer that holds the statusline.

So `let statusline .= &fileencoding` will append the setting for the buffer that has focus, and `let statusline .= '%{&fileencoding}'` will append the setting for the buffer that the statusline is for, which is what you probably want. Just an unfortunate quirk of the vim statusline system.

I mention this because I notice you're doing something like this:

```vim
if &fileencoding !=# ...
  let statusline .= '%{&fileencoding}'
endif
```

Where you probably want this:
```vim
function! MyFileEncoding()
  if &fileencoding !=# ...
    return '[&fileencoding]'
  endif
  return ''
endfunction
...
let statusline .= '%{MyFileEncoding()}'
```

Or this:
```vim
let statusline .= '%{&fileencoding !=# ... ? "[&fileencoding]" : ""}'
```

**Comment by osamuaoki** [comment]
Hi,

On Sat, Aug 31, 2019 at 07:49:43AM -0700, rbong wrote:
> @osamuaoki Very nice config! Keep in mind that executing something outside of a
> statusline item will be in the context of the currently active buffer, and
> executing something inside of a statusline item will be in the context of the
> buffer that holds the statusline, despite the fact that a:current and a:width
> correspond to the buffer that holds the statusline.
> 
> So let statusline .= &fileencoding will append the setting for the buffer that
> has focus, and let statusline .= '%{&fileencoding}' will append the setting for
> the buffer that the statusline is for, which is what you probably want. Just an
> unfortunate quirk of the vim statusline system.
> 
> I mention this because I notice you're doing something like this:
> 
> if &fileencoding !=# ...
>   let statusline .= '%{&fileencoding}'
> endif
> 
> Where you probably want this:
> 
> function! MyFileEncoding()
>   if &fileencoding !=# ...
>     return '[&fileencoding]'
>   endif
>   return ''
> endfunction
> ...
> let statusline .= '%{MyFileEncoding()}'
> 
> Or this:
> 
> let statusline .= '%{&fileencoding !=# ... ? "[&fileencoding]" : ""}'

Thanks.  I will fix it (I am very new to vim script.  I really need to
study and understand...)

Anyway, in the mean time, I have made minor cosmetic changes and pushed
them to repo.  But I haven't included your suggestions.  

Good night for now.

Osamu

**Comment by osamuaoki** [comment]
Hi,

By the way, I was reading vim-lightline code which gave me better coding
for:

NOW:    %{&fenc}
BETTER: %{&fencoding !=# "" ? &fencoding:&encoding}

This is because for some case such as new file, &fencoding is "" while
&encoding may be available.  Interesting corner case.

I now understand what you were talking about ...

On Sat, Aug 31, 2019 at 07:49:43AM -0700, rbong wrote:
> @osamuaoki Very nice config! Keep in mind that executing something outside of a
> statusline item will be in the context of the currently active buffer, and
> executing something inside of a statusline item will be in the context of the
> buffer that holds the statusline, despite the fact that a:current and a:width
> correspond to the buffer that holds the statusline.

I guess what I see odd behavior for git-branch thing may also be this
one.  I will look into code later...

Osamu

**Comment by rbong** [comment]
Thanks, I'm handling this case in the examples now
