### ISSUE TITLE
Way to add new highlight groups?

### ISSUE THREAD

**Issue by runiq** [rbong/vim-crystalline#17]
Is there a way to add new highlighting groups, on a more-or-less ad-hoc basis? I tried using `:highlight CrystallineDirName guibg=#262626` before and after my statusline function, and while the highlight groups seem to be created correctly, they are all 'empty' (i.e. `:highlight CrystallineDirName` shows `CrystallineDirName xxx cleared`).

Can you point me in the right direction? I'm not sure *where* in the plugin code I'm supposed to look for clearing highlights…

**Comment by runiq** [comment]
Turns out vim-crystalline wasn't the culprit: The colorscheme I was using cleared all highlights.

Still, while it's possible to add new ad-hoc highlight groups, vim-crystalline doesn't automatically create separators for them. I initially thought it would be enough to add them to `g:crystalline_supported_sep` since that dict is merged into `g:crystalline_default_supported_sep`.

How would you feel about a PR that patches `crystalline#generate_theme()` to fall back to an existing highlight group if it's not defined in a theme?

**Comment by runiq** [comment]
Turns out this was possible all along with the `CrystallineSetTheme` autocmd:

```vim
function! s:CustomizeCrystalline() abort
	highlight Crystalline guibg=#ff0000
endfunction

augroup MyCrystalline_config
	autocmd!
	autocmd User CrystallineSetTheme call s:CustomizeCrystalline()
augroup END
```

Also works well with recomputing separator HGs now that #21 is merged.

**Comment by rbong** [comment]
Sorry for not catching that... Thank you for your contributions
