### ISSUE TITLE
tmux doesnt show color in status line

### ISSUE THREAD

**Issue by nnorakk** [rbong/vim-crystalline#2]
When I open a tmux session ( default configuration ) I cant see the colours in status line. 

Im using fedora 29 and in my .vimrc has 

" StatusLine Plugin crystalline
function! StatusLine(...)
  return crystalline#mode() . ' %f%h%w%m%r '
endfunction
let g:crystalline_statusline_fn = 'StatusLine'
let g:crystalline_theme = 'dracula'
set laststatus=2

**Comment by rbong** [comment]
I found out that tmux doesn't come with 256 color support by default. You have to either run `export TERM=xterm-256color` before launching vim or run `set term=xterm-256color` in vim. Let me know if that fixes it.

**Comment by rbong** [comment]
Closing this for now... please reopen if that doesn't fix it.
