### ISSUE TITLE
Updated performance measuring script

### ISSUE THREAD

**Issue by runiq** [rbong/vim-crystalline#24]
While trying to measure performance, I've [updated the performance measuring script](https://github.com/rbong/vim-crystalline/files/4356171/compare_linesv2.zip):

- Doesn't require vim-plug (uses git and manual runtimepath manipulation)
- Uses vim's -N (`nocompatible`) argument by default, because my Fedora box's vim installation errored on crystalline without it set
- Runs benchmarks in a temporary directory that is deleted afterwards
- Doesn't overwrite ~/.vimrc anymore, uses vim's `-u path/to/vimrc` instead
- Github-friendly output. An example:

  > Benchmark (x100)              | Time
  > ------------------------------|--------
  > vim-crystalline startup       | 0:00.92
  > vim-crystalline redraw        | 0:00.24
  > lightline.vim startup         | 0:01.20
  > lightline.vim redraw          | 0:00.34
  > vim-airline startup           | 0:03.89
  > vim-airline redraw            | 0:03.42
  > vim-airline optimized startup | 0:03.25
  > vim-airline optimized redraw  | 0:03.01
  > vanilla startup               | 0:00.61
  > vanilla redraw                | 0:00.03
  >
  > <details>
  > <summary>Additional information</summary>
  >
  > Terminal: <code>alacritty</code>
  >
  > Vim:
  > <pre>
  > VIM - Vi IMproved 8.2 (2019 Dec 12 kompiliert am Mar  3 2020 00:00:00)
  > Inklusive der Patches: 1-348
  > Verändert von <bugzilla@redhat.com>
  > Übersetzt von <bugzilla@redhat.com>
  > Riesige Version ohne GUI. Ein- (+) oder ausschließlich (-) der Eigenschaften:
  > +acl               -farsi             -mouse_sysmouse    -tag_old_static
  > +arabic            +file_in_path      +mouse_urxvt       -tag_any_white
  > +autocmd           +find_in_path      +mouse_xterm       -tcl
  > +autochdir         +float             +multi_byte        +termguicolors
  > -autoservername    +folding           +multi_lang        +terminal
  > -balloon_eval      -footer            -mzscheme          +terminfo
  > +balloon_eval_term +fork()            +netbeans_intg     +termresponse
  > -browse            +gettext           +num64             +textobjects
  > ++builtin_terms    -hangul_input      +packages          +textprop
  > +byte_offset       +iconv             +path_extra        +timers
  > +channel           +insert_expand     +perl/dyn          +title
  > +cindent           +job               +persistent_undo   -toolbar
  > -clientserver      +jumplist          +popupwin          +user_commands
  > -clipboard         +keymap            +postscript        +vartabs
  > +cmdline_compl     +lambda            +printer           +vertsplit
  > +cmdline_hist      +langmap           +profile           +virtualedit
  > +cmdline_info      +libcall           -python            +visual
  > +comments          +linebreak         +python3/dyn       +visualextra
  > +conceal           +lispindent        +quickfix          +viminfo
  > +cryptv            +listcmds          +reltime           +vreplace
  > +cscope            +localmap          +rightleft         +wildignore
  > +cursorbind        +lua/dyn           +ruby/dyn          +wildmenu
  > +cursorshape       +menu              +scrollbind        +windows
  > +dialog_con        +mksession         +signs             +writebackup
  > +diff              +modify_fname      +smartindent       -X11
  > +digraphs          +mouse             -sound             -xfontset
  > -dnd               -mouseshape        +spell             -xim
  > -ebcdic            +mouse_dec         +startuptime       -xpm
  > +emacs_tags        +mouse_gpm         +statusline        -xsmp
  > +eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
  > +ex_extra          +mouse_netterm     +syntax            -xterm_save
  > +extra_search      +mouse_sgr         +tag_binary
  >           System-vimrc-Datei: "/etc/vimrc"
  >         Benutzer-vimrc-Datei: "$HOME/.vimrc"
  >  zweite Benutzer-vimrc-Datei: "~/.vim/vimrc"
  >          Benutzer-exrc-Datei: "$HOME/.exrc"
  >       defaults Datei: "$VIMRUNTIME/defaults.vim"
  >      Voreinstellung für $VIM: "/etc"
  >          und für $VIMRUNTIME: "/usr/share/vim/vim82"
  > Übersetzt: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
  > Linken: gcc   -L. -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm  -L/usr/local/lib -Wl,--as-needed -o vim        -lm  -lselinux  -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc
  > </pre></details>

**Comment by runiq** [comment]
Here's a diff between old and new:

```diff
diff --git 1/../compare_lines.sh 2/compare_linesv2.sh
old mode 100644
new mode 100755
index 0e591ab..aa8a81d
--- 1/../compare_lines.sh
+++ 2/compare_linesv2.sh
@@ -1,11 +1,18 @@
 #!/usr/bin/env bash

-# !!! This script temporarily overwrites your .vimrc, back it up before running this !!!
+export LC_ALL=C

 ITER=${ITER:-100}
-VIM=${VIM:-vim}
+VIM=${VIM:-vim -N}
 OUT=${OUT:-line_performance.log}

+declare -A STATUSLINES=( \
+  ["crystalline"]="${CRYSTALLINE_CLONE_URL:-https://github.com/rbong/vim-crystalline}" \
+  ["lightline"]="${LIGHTLINE_CLONE_URL:-https://github.com/itchyny/lightline.vim}" \
+  ["airline"]="${AIRLINE_CLONE_URL:-https://github.com/vim-airline/vim-airline}" \
+  ["fugitive"]="${FUGITIVE_CLONE_URL:-https://github.com/tpope/vim-fugitive}" \
+)
+
 MEASURE_TIME="function! MeasureTime(iter)
     for l:i in range(a:iter)
       vsplit
@@ -17,17 +24,38 @@ MEASURE_TIME="function! MeasureTime(iter)
 endfunction"
 TIME="/usr/bin/time -f %E -o $OUT -a"

+function lognoeol() {
+  printf '%-29s | ' "$*" >> "$OUT"
+}
+
 function log() {
   echo $* >> "$OUT"
 }

-rm "$OUT"
+rm -f "$OUT"
 echo logging to "$OUT"

-cp ~/.vimrc ~/.vimrc.bkp
+echo Creating temporary directory
+readonly OLD_CWD="$(pwd)"
+readonly TEMP_DIR="$(mktemp -dp $OLD_CWD)"
+cd "$TEMP_DIR"

-cat <<EOF > ~/.vimrc
+echo Cloning statusline repositories
+for line in "${!STATUSLINES[@]}"; do
+  git clone --depth=1 "${STATUSLINES[$line]}" "$line"
+done
+sync
+
+lognoeol Benchmark \(x$ITER\)
+log 'Time'
+log ------------------------------\|--------
+
+cat <<EOF > vimrc.crystalline
 $MEASURE_TIME
+set runtimepath^=$TEMP_DIR/crystalline
+set runtimepath^=$TEMP_DIR/fugitive
+set runtimepath+=$TEMP_DIR/crystalline/after
+set runtimepath+=$TEMP_DIR/fugitive/after

 function! StatusLine(current, width)
   return (a:current ? crystalline#mode() . crystalline#right_mode_sep('') : '%#CrystallineInactive#')
@@ -48,113 +76,91 @@ let g:crystalline_theme = 'default'

 set showtabline=2
 set laststatus=2
-
-
-call plug#begin()
-Plug('rbong/vim-crystalline')
-Plug('tpope/vim-fugitive')
-call plug#end()
 EOF

-$VIM -c "PlugInstall | PlugUpdate | qa"
-
-log vim-crystalline startup time X${ITER}:
+lognoeol vim-crystalline startup
 $TIME bash -c "for i in \$(seq '"$ITER"'); do
-  $VIM -c q
+  $VIM -u vimrc.crystalline -c q
 done"
-log

-log vim-crystalline redraw time X${ITER}:
-$TIME $VIM -c "call MeasureTime(${ITER})"
-log
+lognoeol vim-crystalline redraw
+$TIME $VIM -u vimrc.crystalline -c "call MeasureTime(${ITER})"

-cat <<EOF > ~/.vimrc
+cat <<EOF > vimrc.lightline
 $MEASURE_TIME
+set runtimepath^=$TEMP_DIR/lightline
+set runtimepath+=$TEMP_DIR/lightline/after

 set showtabline=2
 set laststatus=2
-
-call plug#begin()
-Plug('itchyny/lightline.vim')
-call plug#end()
 EOF

-$VIM -c "PlugInstall | PlugUpdate | qa"
-
-log lightline.vim startup time X${ITER}:
+lognoeol lightline.vim startup
 $TIME bash -c "for i in \$(seq '"$ITER"'); do
-  $VIM -c q
+  $VIM -u vimrc.lightline -c q
 done"
-log

-log lightline.vim redraw time X${ITER}:
-$TIME $VIM -c "call MeasureTime(${ITER})"
-log
+lognoeol lightline.vim redraw
+$TIME $VIM -u vimrc.lightline -c "call MeasureTime(${ITER})"

-cat <<EOF > ~/.vimrc
+cat <<EOF > vimrc.airline
 $MEASURE_TIME
-
-call plug#begin('~/.vim/plugged')
-    Plug 'vim-airline/vim-airline'
-call plug#end()
+set runtimepath^=$TEMP_DIR/airline
+set runtimepath+=$TEMP_DIR/airline/after
 EOF

-$VIM -c "PlugInstall | PlugUpdate | qa"
-
-log vim-airline startup time X${ITER}:
+lognoeol vim-airline startup
 $TIME bash -c "for i in \$(seq '"$ITER"'); do
-  $VIM -c q
+  $VIM -u vimrc.airline -c q
 done"
-log

-log vim-airline redraw time X${ITER}:
-$TIME $VIM -c "call MeasureTime(${ITER})"
-log
+lognoeol vim-airline redraw
+$TIME $VIM -u vimrc.airline -c "call MeasureTime(${ITER})"

-cat <<EOF > ~/.vimrc
+cat <<EOF > vimrc.airline-optimized
 $MEASURE_TIME
+set runtimepath^=$TEMP_DIR/airline
+set runtimepath+=$TEMP_DIR/airline/after

 let g:airline_extensions = []
 let g:airline_highlighting_cache = 1
-
-call plug#begin('~/.vim/plugged')
-    Plug 'vim-airline/vim-airline'
-call plug#end()
 EOF

-$VIM -c "PlugInstall | PlugUpdate | qa"
-
-log vim-airline optimized startup time X${ITER}:
+lognoeol vim-airline optimized startup
 $TIME bash -c "for i in \$(seq '"$ITER"'); do
-  $VIM -c q
+  $VIM -u vimrc.airline-optimized -c q
 done"
-log

-log vim-airline optimized redraw time X${ITER}:
-$TIME $VIM -c "call MeasureTime(${ITER})"
-log
+lognoeol vim-airline optimized redraw
+$TIME $VIM -u vimrc.airline-optimized -c "call MeasureTime(${ITER})"

-cat <<EOF > ~/.vimrc
+cat <<EOF > vimrc.vanilla
 $MEASURE_TIME
 EOF

-log vanilla startup time X${ITER}:
+lognoeol vanilla startup
 $TIME bash -c "for i in \$(seq '"$ITER"'); do
-  $VIM -c q
+  $VIM -u vimrc.vanilla -c q
 done"
-log

-log vanilla redraw time X${ITER}:
-$TIME $VIM -c "call MeasureTime(${ITER})"
-log
+lognoeol vanilla redraw
+$TIME $VIM -u vimrc.vanilla -c "call MeasureTime(${ITER})"

-log terminal information:
-log $TERM
 log
-
-log version information:
+log '<details>'
+log '<summary>Additional information</summary>'
+log
+log "Terminal: <code>$TERM</code>"
+log
+log Vim:
+log '<pre>'
 $VIM --version >> "$OUT"
+log '</pre></details>'

-cp ~/.vimrc.bkp ~/.vimrc
+cd "$OLD_CWD"
+cp "$TEMP_DIR/$OUT" .

-cat "$OUT"
+echo Removing $TEMP_DIR:
+rm -rf "$TEMP_DIR"
+
+# cat "$OUT"
```

**Comment by runiq** [comment]
I'm going to rework this tomorrow to match the format in https://github.com/rbong/vim-crystalline/pull/20#issuecomment-601414291.

Edit: [Done](https://github.com/rbong/vim-crystalline/files/4356994/compare_linesv3.zip). Example output:

> Benchmark (x100) | Startup | Redraw
> -|-|-
> crystalline |0:00.82 | 0:00.21
> lightline   |0:01.04 | 0:00.30
> airline     |0:03.30 | 0:02.92
> airline-opt |0:02.85 | 0:02.51
> vanilla     |0:00.56 | 0:00.03
>
> <details>
> <summary>Additional information</summary>
>
> Terminal: alacritty
>
> Vim:
> <pre>
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2020 00:00:00)
> Included patches: 1-348
> Modified by <bugzilla@redhat.com>
> Compiled by <bugzilla@redhat.com>
> Huge version without GUI.  Features included (+) or not (-):
> +acl               -farsi             -mouse_sysmouse    -tag_old_static
> +arabic            +file_in_path      +mouse_urxvt       -tag_any_white
> +autocmd           +find_in_path      +mouse_xterm       -tcl
> +autochdir         +float             +multi_byte        +termguicolors
> -autoservername    +folding           +multi_lang        +terminal
> -balloon_eval      -footer            -mzscheme          +terminfo
> +balloon_eval_term +fork()            +netbeans_intg     +termresponse
> -browse            +gettext           +num64             +textobjects
> ++builtin_terms    -hangul_input      +packages          +textprop
> +byte_offset       +iconv             +path_extra        +timers
> +channel           +insert_expand     +perl/dyn          +title
> +cindent           +job               +persistent_undo   -toolbar
> -clientserver      +jumplist          +popupwin          +user_commands
> -clipboard         +keymap            +postscript        +vartabs
> +cmdline_compl     +lambda            +printer           +vertsplit
> +cmdline_hist      +langmap           +profile           +virtualedit
> +cmdline_info      +libcall           -python            +visual
> +comments          +linebreak         +python3/dyn       +visualextra
> +conceal           +lispindent        +quickfix          +viminfo
> +cryptv            +listcmds          +reltime           +vreplace
> +cscope            +localmap          +rightleft         +wildignore
> +cursorbind        +lua/dyn           +ruby/dyn          +wildmenu
> +cursorshape       +menu              +scrollbind        +windows
> +dialog_con        +mksession         +signs             +writebackup
> +diff              +modify_fname      +smartindent       -X11
> +digraphs          +mouse             -sound             -xfontset
> -dnd               -mouseshape        +spell             -xim
> -ebcdic            +mouse_dec         +startuptime       -xpm
> +emacs_tags        +mouse_gpm         +statusline        -xsmp
> +eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
> +ex_extra          +mouse_netterm     +syntax            -xterm_save
> +extra_search      +mouse_sgr         +tag_binary
>    system vimrc file: "/etc/vimrc"
>      user vimrc file: "$HOME/.vimrc"
>  2nd user vimrc file: "~/.vim/vimrc"
>       user exrc file: "$HOME/.exrc"
>        defaults file: "$VIMRUNTIME/defaults.vim"
>   fall-back for $VIM: "/etc"
>  f-b for $VIMRUNTIME: "/usr/share/vim/vim82"
> Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
> Linking: gcc   -L. -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm  -L/usr/local/lib -Wl,--as-needed -o vim        -lm  -lselinux  -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc
> </pre></details>

**Comment by rbong** [comment]
Thank you! [I've updated the script to your version](https://raw.githubusercontent.com/wiki/rbong/vim-crystalline/scripts/compare_lines.sh). Just one change, had invisible errors on my system because `$VIM` was set already. I added `set -e` so errors would be more visible and changed `$VIM` to `$VIM_CMD`.
