### ISSUE TITLE
Tabs/Buffers generated by Crystalline cannot be clicked.

### ISSUE THREAD

**Issue by magpie514** [rbong/vim-crystalline#3]
Ubuntu 19.04 64b, vim 8.1, vim-crystalline just installed through Plug:
I gave crystalline a spin but noticed a little issue with the output of bufferline. With tabline='' I get tabs I can click on and a close button. But, if I use the output of bufferline(0,0,1) I instead can only cycle through tabs regardless on where I click.
I'm an absolute vim novice so I just looked around to see what this was about and found some simple function to just print tabs out, just to have matching modal colors for the time being, so my current setup looks like:
```
function MyTabLabel(n)
	let l:buflist = tabpagebuflist(a:n)
	let l:winnr =   tabpagewinnr(a:n)
	let l:bufname = bufname(buflist[l:winnr -1])
	return empty(l:bufname) ? 'EMPTY' : l:bufname
endfunction

function! TabLine()
	let s = ''
	for i in range(tabpagenr('$')) " select the highlighting
		if i + 1 == tabpagenr()
			let s .= crystalline#mode_color()
		else
			let s .= '%#CrystallineTab#'
		endif
		let s .= '%' . (i + 1) . 'T' 		" set the tab page number (for mouse clicks)
		let s .= ' %{MyTabLabel(' . (i + 1) . ')} '
	endfor
	let s .= '%#CrystallineTabFill#%T' 	" after the last tab fill with TabLineFill and reset tab page nr
	if tabpagenr('$') > 1 	" right-align the label to close the current tab page
		let s .= '%=%#TabLine#%999X❌'
	endif
	return s
endfunction
let g:crystalline_tabline_fn = 'TabLine'
let g:crystalline_statusline_fn = 'StatusLine'
let g:crystalline_theme = 'onedark'

set showtabline=2
set laststatus=2
```
I noticed the function I quickly adapted had that "set tab page number" comment, so I assume that's what's missing from the Crystalline-generated one?

**Comment by rbong** [comment]
Thanks for drawing attention to this, I should be able to fit this in an update coming in the next few days. If you need it soon, I'll have it fixed before that on the `dev` branch.

**Comment by magpie514** [comment]
I can wait until it's in master, but I'll keep an eye on the dev branch. Thank you for the quick reply!

**Comment by rbong** [comment]
No problem. It should be fixed on the dev branch now. Note that buffers will not be clickable, only tabs. Vim doesn't have an item that will allow me to do that yet AFAIK.

**Comment by rbong** [comment]
This should now work on master

**Comment by magpie514** [comment]
Works perfectly, thank you!
