### ISSUE TITLE
Have function to return next / prev buffer

### ISSUE THREAD

**Issue by srcrip** [rbong/vim-crystalline#38]
It'd be really nice to have a built in function from this plugin to return the next or prev buffer, so that you can easily move between only the buffers that are displayed by crystalline.

**Comment by rbong** [comment]
If you use the default hiding behavior, you can use [vim-unimpaired](https://github.com/tpope/vim-unimpaired) and `[b`/`]b` to navigate between the prev/next buffer. Might be a while before I can get to this feature - PRs welcome.

**Comment by srcrip** [comment]
Nice, thats a convenient workaround.
