### ISSUE TITLE
i want to change tabline info 

### ISSUE THREAD

**Issue by ghost** [rbong/vim-crystalline#40]
My tabline shows filepath and name. My statusline too. That's double. Can I have tabline info without a path?
Please give me an example.

**Comment by rbong** [comment]
Sorry for the delayed response. This has become much easier in version 1.0.0 that was just released:

```vim
function! g:CrystallineTabFn(tabnr, bufnr, max_width, is_sel) abort
  let l:tab = ' ' . a:tabnr . ' '
  return [l:tab, strchars(l:tab)]
endfunction

function! g:CrystallineTablineFn() abort
  return crystalline#DefaultTabline()
endfunction
```

Please let me know if you have any more questions. I have also opened [discussions](https://github.com/rbong/vim-crystalline/discussions).
