### ISSUE TITLE
exclude quickfix from tabline

### ISSUE THREAD

**Issue by dbarrosop** [rbong/vim-crystalline#5]
Is it possible to exclude the quickfix from the tabline? Something like this: vim-airline/vim-airline/issues/244

Thanks and awesome job :)

**Comment by dbarrosop** [comment]
Ok, that turned out to be easy, I sent you a PR :)

**Comment by rbong** [comment]
Thank you for the PR! I've been meaning to rework how buffers are hidden so I just fixed and tested this at the same time though. It should now be fixed on master.
